version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

volumes:
  mongodb_data:
