server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cache:
    cache-names: getPropostaWorkflowStub

queue:
  analise:
    request: analise_request
    response: analise_response

